*** Variables ***
${logo}=                      //android.widget.ScrollView[@content-desc="test-Login"]/android.view.ViewGroup/android.widget.ImageView[1]
${username_field}=            //android.widget.EditText[@content-desc="test-Username"]
${password_field}=            //android.widget.EditText[@content-desc="test-Password"]
${login_btn}=                 //android.view.ViewGroup[@content-desc="test-LOGIN"]/android.widget.TextView
${error_message}=             //android.view.ViewGroup[@content-desc="test-Error message"]/android.widget.TextView
